### PR TITLE
Create stuttgart

### PR DESCRIPTION
**Pull request by areyer**
Not yet part of ic-vpn, but about to adjust IP-ranges.

### CODE REVIEW

**Comment by mweinelt** [comment]
Thats great to here, thanks and welcome!

**Comment by leeps** [comment]
Any reason why you need a larger than usual allocation, @areyer ?

**Comment by areyer** [comment]
On Sat, Jun 27, 2015 at 02:51:35PM -0700, leeps wrote:
> Any reason why you need a larger than usual allocation, @areyer ?

it is Freifunk Stuttgart, actually the whole area around Stuttgart,
check http://gw01.freifunk-stuttgart.de/map/, you have to zoom out.
Due to routing protocol issues (batman), we need to do several/many
 segments and due to a few hotspots with many users, the single
gateway needs to be able to assign many IPs. We have 10 of them.
Actually we considered finding a /14, however, there seems to be none
available and we hope to fit within the /15.

Kind regards,
	    Adrian Reyer
-- 
LiHAS - Adrian Reyer - Hessenwiesenstraße 10 - D-70565 Stuttgart
Fon: +49 (7 11) 78 28 50 90 - Fax:  +49 (7 11) 78 28 50 91
Mail: lihas@lihas.de - Web: http://lihas.de
Linux, Netzwerke, Consulting & Support - USt-ID: DE 227 816 626 Stuttgart

**Comment by basros** [comment]
Can you please elaborate on your mesh-architecture? 
Since your mesh is based on gluon/batadv, I have to assume that you run centralized synced DHCP-servers. 
Your statistics show <1000 clients. I don't get why you need over 100k IPs. Please keep IP-space free for other/future communities.

**Comment by areyer** [comment]
On Sat, Jun 27, 2015 at 03:19:09PM -0700, basros wrote:
> Can you please elaborate on your mesh-architecture? 
> Since your mesh is based on gluon/batadv, I have to assume that you run centralized synced DHCP-servers. 
> Your statistics show <1000 clients. I don't get why you need over 100k IPs. Please keep IP-space free for other/future communities.

We have seperated dhcp-servers with seperated ranges per gateway. 10
gateways. We already have single mesh-nodes with >300 Clients and
currently offer up to 2k IPs per gateway/segment.
Unfortunately batman doesn'tr seem to route dhcp-requests to other
dhcp-servers if the one it chose has no free IPs left. Clients just end
up without IPs.
As a result, with our current dezentralized managed structure, we need
to be able to feed IPs to all possible client.
Even with only 10 segments, 10 gateways and 1000 IPs it would be 100k
IPs.
It won't work this way in the long run, however, management traffic
kills the infrastructure atm. Due to geographical topology and node
distribution in southern germany we are rarely able to mesh between
nodes, this is why almost every node has a seperate vpn-gatewaay access
atm.
However, I just entered the IP-range into the git tree as the one who
'reserved' them at http://wiki.freifunk.net/IP-Netze.

Regards,
	Adrian
-- 
LiHAS - Adrian Reyer - Hessenwiesenstraße 10 - D-70565 Stuttgart
Fon: +49 (7 11) 78 28 50 90 - Fax:  +49 (7 11) 78 28 50 91
Mail: lihas@lihas.de - Web: http://lihas.de
Linux, Netzwerke, Consulting & Support - USt-ID: DE 227 816 626 Stuttgart

**Comment by leeps** [comment]
B.A.T.M.A.N. gateway mode makes clients translate DHCP DISCOVER broadcast into unicast packets and routes them to the selected gateway only, which is the scenario you describe. If you aren't really meshing (and thus don't care about wasting airtime with broadcasts), you could turn off gateway mode so DHCP DISCOVER will stay broadcast.

Also, better management of gateways should reduce the number ob spare IPs you need to hold:
- You don't need every gateway to be part of every segment.
- You can limit fastd connections to balance the amount of nodes per gateway.

Your own wiki[1] currently lists less than 10 active gateways and only 4 segments. I recognize the article may be incomplete, as documentation often is, but if you were trying to justify your need for a larger than usual IP allocation, you should aim to at least keep these docs current.


*I'm not trying to tell you how to run your network*, but if IP space for Freifunk communities is depleted and new communities need some, those communities with the largest allocations will probably be looked to first.

[1] https://wiki.freifunk-stuttgart.net/technik:gateways:gateway-liste

**Comment by areyer** [comment]
On Sun, Jun 28, 2015 at 04:46:05AM -0700, leeps wrote:
> B.A.T.M.A.N. gateway mode makes clients translate DHCP DISCOVER broadcast into unicast packets and routes them to the selected gateway only, which is the scenario you describe. If you aren't really meshing (and thus don't care about wasting airtime with broadcasts), you could turn off gateway mode so DHCP DISCOVER will stay broadcast.

Actually we *want* to mesh, just current node distribution won't allow
us for now. Within 251 days since first ffs-firmare we made 300 nodes,
now, 28 days later we are at 346 active nodes. Active 'marketing' only
started a few months ago.

> Also, better management of gateways should reduce the number ob spare IPs you need to hold:
> - You don't need every gateway to be part of every segment.
> - You can limit fastd connections to balance the amount of nodes per gateway.

Well, we want every node to be a part of every segment. wen don't want
the net to depend on few individuals.
We considered limiting the amount of fastd connections and it lessens
the effect to a small extend. As of now we support 2 (maybe 3) schools
and at least 2 refugee homes, there we have many users at the same
node/within the same segment. It is up to 300 concurrent users on a
single node (with AP infrastructure in the background) already and the
place in question has 1700 people.

> Your own wiki[1] currently lists less than 10 active gateways and only 4 segments. I recognize the article may be incomplete, as documentation often is, but if you were trying to justify your need for a larger than usual IP allocation, you should aim to at least keep these docs current.

The article is there since about yesterday, we agreed on at least 5
segemnts around Stuttgart and we have a tendency to take over smaller
communities for joint efforts. E.g. Freifunk Weinstadt and Freifunk
Thalheim.

> *I'm not trying to tell you how to run your network*, but if IP space for Freifunk communities is depleted and new communities need some, those communities with the largest allocations will probably be looked to first.

You are very welcome. We are on 172.21.0.0/16 as well atm, however,
dn42 asked us to free the space, this is why we are moving at all. I am
quite confident to use up a good deal of the IPs with real devices.
Apart from that, the yaml file already knows about delegated networks.
Be aware, I am just the one who migrated a line from
http://wiki.freifunk.net/IP-Netze / "weitere (regionale,
deutschsprachige) IP-Netze" to icvpn-meta. And I am part of Freifunk
Stuttgart. I am not the one who states how things run.

Regards,
	Adrian
-- 
LiHAS - Adrian Reyer - Hessenwiesenstraße 10 - D-70565 Stuttgart
Fon: +49 (7 11) 78 28 50 90 - Fax:  +49 (7 11) 78 28 50 91
Mail: lihas@lihas.de - Web: http://lihas.de
Linux, Netzwerke, Consulting & Support - USt-ID: DE 227 816 626 Stuttgart

**Comment by leeps** [comment]
Thanks for explaining your expected growth based on the last year. I now understand better why you want a larger IP space.

I still think your gateway setup is the biggest negative factor in terms of IP space usage efficiency. This would be one of the aspects I would look into if we would have to redistribute IP space for newer communities. It might not look so bad in the future, when you have higher saturation of your IP space, but I also expect 10/8 to be full within the next 12 months as more and more communities emerge.

Please forward my concerns (or a link to this thread, [1]) to the people responsible for IP numbering and allocations at Freifunk Stuttgart.

[1] https://github.com/freifunk/icvpn-meta/pull/168

**Pull request merged**
