### PR TITLE
Create jichi

### PR DESCRIPTION
**Pull request by jiderlesi**

### CODE REVIEW

**Comment by wusel42** [comment]
What's "jichi"?

Besides, in-addr.arpa and ip6.arpa domains are wrong. An /18 would give you 64 in-addr.arpa zones, and the ip6.arpa looks somehow wrong.

**Comment by jiderlesi** [comment]
Thank you very much, I will check it.
jichi is a non-profit organization we are registering, we wanna make some freifunk and icvpn in our office and home, so we wanna apply a ASN here.

**Comment by jiderlesi** [comment]
It's ok now, you can check it.thanks.

**Comment by jiderlesi** [comment]
> 
> 
> What's "jichi"?
> 
> Besides, in-addr.arpa and ip6.arpa domains are wrong. An /18 would give you 64 in-addr.arpa zones, and the ip6.arpa looks somehow wrong.

hello, I'm sorry to bother you, but could you recheck it and tell me more?Thank you.

**Comment by marek22k** [comment]
@jiderlesi ICVPN is rather Freifunk and this repo (as far as I perceive) is not quite active. You can alternatively join another network. These should actually all be connected. For example dn42, NeoNetwork or ChaosVPN.

**Pull request closed without merging**
