### PR TITLE
Delete Hannover

### PR DESCRIPTION
**Pull request by AiyionPrime**
> FFH doesn't use icvpn anymore, which wont change in foreseeable
> future.
> 
> FFH still uses fdca:ffee:8::/64, as well as 10.2.0.0/16.

I am not sure, whether it's useful to leave the community as a placeholder for the ranges.

@marek22k informed us that we'd still be listed here as active community, sorry we left this unclean.

### CODE REVIEW

**Comment by AiyionPrime** [comment]
@moridius, @1977er or @lemoer any objections?

**Comment by lemoer** [comment]
@AiyionPrime LGTM.

**Comment by wusel42** [comment]
> FFH still uses fdca:ffee:8::/64, as well as 10.2.0.0/16.

Well, if you delete Hannover's entry, returning to ICVPN or any possible successor/alternative might be impossible with regards to IPv4, and the IPv6 ULAs doesn't look too random either. Your choice — please confirm final deletion ;)

**Comment by 1977er** [comment]
After reading wusel's comment, I think we should leave it there. Doesn't hurt. I think we can handle one mislead person per decade.

**Comment by AiyionPrime** [comment]
I think it would be unwise for other communities to claim our blocks, as we are still using them and have no intention to stop.
I'm fine with leaving Hanovers info in here, as long as there's a way to make clear we are not interested in peerings via icvpn any longer.

We'd like to save others the time to contact us about it, that's all.
The used ip address spaces are 'registered' in the freifunk wiki, not sure how much it helps other communities to avoid them, if we left this entry in some altered form here.

**Comment by wusel42** [comment]
> I think it would be unwise for other communities to claim our blocks, as we are still using them and have no intention to stop. I'm fine with leaving Hanovers info in here, as long as there's a way to make clear we are not interested in peerings via icvpn any longer.
> 
> We'd like to save others the time to contact us about it, that's all.

You'd join ICVPN by deploying the stuff in the icvpn repo these days, IMHO; no contacting for individual sessions anymore.

> The used ip address spaces are 'registered' in the freifunk wiki,

... which table has been replaced by icvpn-meta for all practical uses, AFAICS.

**Comment by wusel42** [comment]
> I think we can handle one mislead person per decade.

If it's only about that spamming dn42 guy seeking peering partners: legt Euch einfach wieder hin ;-)

**Comment by lemoer** [comment]
From my side, I think, we are not rejoining the icvpn in the future. If we were to do this, we would only connect to ipv6.

So, from my side, this PR could be merged.

**Comment by AiyionPrime** [comment]
As @lemoer said, we are unlikely to rejoin; but are leaving our "space reservation" here for others to avoid trouble in the future.
If someone wants us to leave, let us know. Thanks!

**Pull request closed without merging**
