### PR TITLE
larger ip space for ff niersufer

### PR DESCRIPTION
**Pull request by fragstone**

### CODE REVIEW

**Comment by dracoTrier** [comment]
why do you need a /15? your website says "Insgesamt 112 Knoten, davon 92 online, 115 Clients, 2 Gateways"
A /16 already gives you more then 64000 IP addresses.

**Comment by fragstone** [comment]
yes its correct. the reason for that is that we plan to create own l2 networks for up to seven sities. 
For that its actual easier to segment it with an bigger ip space. Additional we have plans to bring local supernodes in mg so that we must hold one or two subnets /20 in the range of this site.

**Comment by dracoTrier** [comment]
then split the /16 as required and use the IP address space efficiently. I don't see why you need more then 64000 IP addresses in the near future. Please explain your usage-plan and splitting a bit more.

**Comment by nazco** [comment]
I'm of the same opinion like @dracoTrier. There is enough space in your current allocation, you just have to plan things right. Btw. this is the same kind of bad network planing happening in the internet for years. If you assign each site/city a /19 and for each gateway (supernode) an /22 you'll have enough space. I'm sure your gateways wouldn't survive even 1024 simultaneous clients.

**Pull request closed without merging**
