### PR TITLE
add Freemesh Denmark

### PR DESCRIPTION
**Pull request by dvarum12**
plz accept this and help me later with ipv6

### CODE REVIEW

**Comment by Ranlvor** [comment]
You do not seem do possess freemesh.dk (yet).
```
;; QUESTION SECTION:
;freemesh.dk.                   IN      A

;; AUTHORITY SECTION:
dk.                     600     IN      SOA     b.nic.dk. tech.dk-hostmaster.dk. 1472299260 600 300 1814400 600
```
 If you get this domain here but not in the official DNS it could lead to confusion. So I'd suggest registering the domain in the official DNS before proceeding here or to drop it here until you have it in the official DNS. You can alter your pull-request by pushing additional commits onto your branch patch-1 in your repository https://github.com/dvarum12/icvpn-meta.git.

I'll look stuff up about IPv6 and edit this post later.

**Comment by mweinelt** [comment]
Just generate a unique ULA prefix here: http://unique-local-ipv6.com/

**Comment by Ranlvor** [comment]
Uh, that one is nice *bookmark*

**Comment by rubo77** [comment]
jetzt sollte die domain da sein

**Comment by mweinelt** [comment]
That is not  the case.

**Comment by rubo77** [comment]
I mean: They have reserved it already, out just takes some workingdays for a .dk domain to register.

So is the rest fine like this?

I help them getting up the gateway running and it would be a quite useless problem if we would have to change any basic ips later.

**Comment by wusel42** [comment]
Just drop the .dk enty for now, it's a bit useless anyway, as it directs some (most?) communities to resolve an official domain via ICVPN paths. Public DNS is supposed to work always; the domain entry in this repo is to support non-official TLDs without needing a complete alternate DNS root system. (In case freemesh.dk wants to provide split-horizon DNS, i. e. delivering different info to public and ICVPN queries, respectively, the entry of course would make sense again. But still, no need to hurry there, so just wait until it's in the public DNS.)

**Pull request merged**
