### PR TITLE
Delegate subnet to FF3L

### PR DESCRIPTION
**Pull request by kpanic23**
new FF3L backbone infrastructure for FFFR

### CODE REVIEW

**Comment by mweinelt** [comment]
@marku89 Please confirm this change.

**Comment by egmont1227** [comment]
Can this be merged?

**Comment by kpanic23** [comment]
In Freiburg, all of the admins had moved on.
The remaining Freifunker did contact us for help.
So in order to help preserve a working Freifunk network in Freiburg, we adopted their nodes and are now running them in their own domain on the FF3L backend. 
Just have a look at freifunk-karte.de:
https://www.freifunk-karte.de/?lat=48.00187&lng=7.8257&z=12&l=Nodes

Since our legacy IP /16 is nearly exhausted, we have used a slice of the original FFFR IP space (They were only using half of their /16) for their three new domains.

**Comment by wusel42** [comment]
@kpanic23 If "Freifunk Freifunk" is either an empty shell and/or run by FF3L now, wouldn't it be cleaner to hand over "freiburg" to the FF3L maintainers? Can "the remaining Freifunker" acknowledge that move?

**Pull request merged**
