### PR TITLE
Splitted the network "VfN-Veranstaltungsnetzwerk"

### PR DESCRIPTION
**Pull request by kevin-olbrich**

### CODE REVIEW

**Comment by mweinelt** [comment]
Not really sure about what is the purpose of this commit.

**Comment by tcatm** [comment]
icvpn-meta does not require such detailed information about networks. It's up to the community to document their networks in their websites.

**Comment by leeps** [comment]
@mweinelt Whoever has the most coins obviously has the most money ;)

**Comment by kevin-olbrich** [comment]
We are migrating to smaller networks.

**Comment by mweinelt** [comment]
Yes, but the allocation stays pretty much the same. Migrating to smaller networks in the context of this registry would mean dropping allocations.

**Comment by kevin-olbrich** [comment]
Currently this is only a preparation to release them later when no active devices are in one of them.

**Comment by mweinelt** [comment]
Fair enough.

**Pull request merged**
