### PR TITLE
Freemesh Ireland

### PR DESCRIPTION
**Pull request by Marlow925**
Freemesh Ireland is IPv6 only. We have our own AS and PIv6 allocations from RIPE. We use NAT64 for IPv4 connectivity.

Our website can be found at http://www.freemesh.ie/

### CODE REVIEW

**Comment by Ranlvor** [comment]
```
Checking ireland
 Last part of BGP addresses differs: {145, 91} (ireland)
 Last part of BGP addresses differs: {146, 92} (ireland)
```
We have a policy that in decimal the IPv4 and IPv6-Adresses of the Gateways should match. On your adress the decimal of the IPv4 and the hexadecimal of the IPv6 match.

You could use this adresses:
```
- [10.207.0.91, 'fec0::a:cf:0:5b']
- [10.207.0.92, 'fec0::a:cf:0:5c']
```

**Comment by Marlow925** [comment]
Hi, 
I had a look through the lists etc. and couldn't find a clear pattern. The Readme does not refer to any policy, what to use, so I guestimated it.

I've adjusted the patch now to the suggested IPv6 gateway addresses.

**Comment by FreifunkUFO** [comment]
if your network doenst have intercity-vpn connection, is ipv6 only, if you have own AS and IPv6 adresses so there is NO NEED for entry within this repository.

please check Freifunk-API instead to get information on the freifunk-map:
https://github.com/freifunk/api.freifunk.net

**Comment by wusel42** [comment]
@FreifunkUFO Since not all communities have or use public v6, connecting to the ICVPN still can make sense even with public v6; OTOH, if no ICVPN connectivity is planned, there's no need to enter any data into this repository.

**Comment by Marlow925** [comment]
@FreifunkUFO That statement was a bit shortsighted :)

Freemesh Ireland may not have IPv4 and may have public IPv6 and an AS, BUT .. and this is the big BUT: not every Freifunk community has an IPv6 default route to the world. 

Some communities elect only to give access to the networks, that are within the Freifunk communities. 

Also, as I already stated in my first comment, we do use NAT64 for IPv4, meaning, that users in the Freemesh Ireland network can access services within the Freifunk communities on 10.x RFC1918 ip addressing. But for that, intercity VPN still would be needed.

And then there's the last item, that the freifunk/freemesh internal DNS is not accessible via the internet (specificly the .fmie domain). This only gets distributed (if implemented by the individual Freifunk communities) by the information provided as part of the intercityvpn.

**Pull request merged**
