### PR TITLE
Delegation remscheid

### PR DESCRIPTION
**Pull request by kevin-olbrich**

### CODE REVIEW

**Comment by mweinelt** [comment]
Please rebase this pull request.

**Comment by kevin-olbrich** [comment]
@mweinelt Are you sure I need to rebase this? I made individual commits based on head.

**Comment by mweinelt** [comment]
Github just states: `We can’t automatically merge this pull request.`

**Comment by kevin-olbrich** [comment]
I will just make a new branch based on head.

**Pull request closed without merging**
