### PR TITLE
Adding Ansbach & sister communities

### PR DESCRIPTION
**Pull request by stesie**
This "migrates" the old, but still active network allocations
of Ansbach, Emskirchen & Neuendettelsau from the Wiki scheme
to here.  (The /24 networks listed)

Besides this allocates new /18 networks for those three
networks, since the /24 allocations from the test installation
regularly hit IP address capacity recently.

Moreover one /18 allocation for Heilsbronn, a new community
to come nearby.

Signed-off-by: Stefan Siegl <stesie@brokenpipe.de>

### CODE REVIEW

**Comment by leeps** [comment]
The e-mail addresses are correct for every community?

**Comment by stesie** [comment]
Yes, they are.  Currently we don't have noc@ addresses for each of the sister communities.

After all Ansbach more or less is the "primary" site.  The other cities are pretty close and all of them share the same gateway servers

**Comment by leeps** [comment]
OK, perfect. It seemed strange that one community has their own and others are using Ansbach's, but since you confirmed, all is well :)

No v6 though? ;)

**Comment by mweinelt** [comment]
Please allocate networks with a prefixlength of up to 22 bit, 24 bit allocations are a bit small and leave no place for further expansion.

**Comment by leeps** [comment]
@mweinelt Apparently those are legacy netblocks, hence the bigger /18 allocations...

**Comment by mweinelt** [comment]
@leeps: Not the `/18` allocations are an issue, the `/24` ones are.

**Comment by stesie** [comment]
@leeps you're right, IPv6 was missing.  I've pushed another commit that should fix this.

@mweinelt you're right, the `/24` are too small -- but currently in use, hence I wanted to add them here (for now). We're willing to deprecate them, and hence allocating /18 networks for each community so we can replace the older ones ... and finally delete the /24 allocations from here

**Comment by mweinelt** [comment]
Ok, that is acceptable in my opinion. Thanks :+1:

**Pull request merged**
