### PR TITLE
Delegation solingen

### PR DESCRIPTION
**Pull request by kevin-olbrich**

### CODE REVIEW

**Comment by mweinelt** [comment]
Please also rebase, when pulling from master, that way we will not have those unnecessary merge commits.

```
git remote add freifunk https://github.com/freifunk/icvpn-meta.git
git pull -r freifunk master
```

**Comment by mweinelt** [comment]
The community file was created by @phi-psi, please ACK or NACK this change.

**Comment by kevin-olbrich** [comment]
Sorry, this PR was accidently pushed to the base repo. I just wanted to reference it to https://github.com/freifunk/icvpn-meta/pull/144

**Comment by RubenKelevra** [comment]
Well @phi-psi created a conflict with an existing community-file. It was just not delegated to a seperate file, though.

We had many requests from solingen, had two spinoff-events. So want to start here, we do announce a network for solingen since some month.

Since Freifunk Rheinland used to had some nodes there, we was asking for over three month without any reaction, so we asked them if its okay to restart there with an new network. @nomaster agreed.

We don't want to start two communitys at solingen, so it would be nice from @phi-psi when he would contact me privatly with contact informations from the freifunkers at solingen.

So we can help to initialize a discussion at this community to solve the issue.

//cc @mweinelt

**Comment by mweinelt** [comment]
This pull request does not remove the allocation in the `vfnnrw` community file, we therefore have a collision.

Also about those collisions, I'm not yet sure how we handle them:
```
 IPv6 Network overlap: vfnnrw (2001:bf7:100::/44), leverkusen (2001:bf7:100:2144::/64)
 IPv6 Network overlap: vfnnrw (2001:bf7:100::/44), solingen (2001:bf7:100:212::/64)
 IPv6 Network overlap: vfnnrw (2001:bf7:100::/44), bottrop (2001:bf7:100:2041::/64)
 IPv6 Network overlap: vfnnrw (2001:bf7:100::/44), gronau (2001:bf7:100:4859::/64)
 IPv6 Network overlap: vfnnrw (2001:bf7:100::/44), altdorf (2001:bf7:100:871::/64)
 IPv6 Network overlap: vfnnrw (2001:bf7:100::/44), hueckeswagen (2001:bf7:100:2192::/64)
 IPv6 Network overlap: vfnnrw (2001:bf7:100::/44), remscheid (2001:bf7:100:2191::/64)
 IPv6 Network overlap: vfnnrw (2001:bf7:100::/44), kuerten (2001:bf7:100:2268::/64)
```
Easiest would be if you removed the `/44` from the `vfnnrw` file after you delegated all networks.

**Comment by RubenKelevra** [comment]
I think the easiest is to allocate any /64 on it's own, in vfnnrw and every delegated community :)

I'm going to make a pull request this evening.

**Pull request closed without merging**
