### PR TITLE
Create zollernalb

### PR DESCRIPTION
**Pull request by jlebherz**
We want to establish freifunk in region zollernalb.

### CODE REVIEW

**Comment by Ranlvor** [comment]
Quot of the Readme:
````
If you need more than a /18 in one community or city you need a very good explaination, why you do need it.
````
What's your explaination?

**Comment by jlebherz** [comment]
The explanation is quite simple, we want freifunk not in a city but in the entire area Zollernalb, establish many cities like Albstadt, Balingen, Hechingen but also in municipalities such Biesingen, Bitz, Winterlingen, Strassberg etc.
We are also trying to expand further in the direction of Sigmaringen, Danube Valley.

**Comment by Ranlvor** [comment]
Most of the communitys cover an area. You could start with a smaller net and exand when needed. According to [this visualisation](http://netblocks.icvpn.starletp9.de/registry.html) there is much space for small nets lower than your net causing other communitys not to fragment this free space by accident.

**Comment by jlebherz** [comment]
Which prefix would you recommend us instead

**Comment by Ranlvor** [comment]
I'd suggest up to /20 per mesh (for 2.000 concurrent users + some extraIPs for larger DHCP-timeouts). That's already a realy big mesh and IMHO BATMAN does not scale to that dimensions.

**Comment by mweinelt** [comment]
TTL will exceed on 19/09/2016.

**Pull request closed without merging**
