### PR TITLE
Add Euskirchen

### PR DESCRIPTION
**Pull request by k3v1n-eu**

### CODE REVIEW

**Comment by Ranlvor** [comment]
What is this icvpn-meta-File you added? Could you please remove it?

**Comment by k3v1n-eu** [comment]
Removing? I want to Add Euskirchen to the IC-VPN. Isn't it the right way?

**Comment by Ranlvor** [comment]
You added a file „icvpn-meta“. This file contians the string „Subproject commit d7a65f54a970017222aed94c428bd1d44231940a“. I want you to remove the file „icvpn-meta“ because I do not see any reason it should be in the repository. When you removed the file „icvpn-meta“ I think this Pull-Request is ready to get merged.

**Comment by Ranlvor** [comment]
Perhaps german works better.

Euskirchen kann gerne rein, aber diese Datei namens icvpn-meta macht keinen Sinn. Wenn du die weg machst nehme ich Euskirchen gerne auf.

**Pull request closed without merging**
