### PR TITLE
Großreinemachen 2018.2

### PR DESCRIPTION
**Pull request by skorpy2009**
Removed all hosts offline for at least 14 days.

I would not care for asking the "maintainers" once more. I asked some via IRC, for all sessions still down, no one cared...

### CODE REVIEW

**Comment by wusel42** [comment]
There's a bloody mailing list for god's sake, and that's part of the stuff that's certainly on-topic there  ("This list is for the communication of the operators of the intercity VPN") — so please head out of the funky chat rooms and inform over proper channels what issue you see/face.

**Comment by ambassador86** [comment]
Is there any automatic montoring notification in place. If I knew there is a problem earlier could take care faster for my node.

**Comment by ambassador86** [comment]
chemnitz1 is back online

**Comment by andibraeu** [comment]
weimar is still online... we had some network issues last week. It's the same for berlin.

Are there any reasons to do it that hard way?

**Comment by skorpy2009** [comment]
icvpn_weimar1 is still down since I have monitoring data (29.01.2018 23:13)

**Comment by wusel42** [comment]
FTR, kreisgt_fks (which is v6 only) is up (again) as well. 

root@icvpn-fks:~# birdc6 show proto | grep BGP | grep Est
e_ffgt_Tbgpfks01 BGP      mesh     up     2018-02-14  Established   
bodensee1 BGP      mesh     up     2018-02-18  Established   
bremen2  BGP      mesh     up     2018-02-18  Established   
bremen5  BGP      mesh     up     2018-02-18  Established   
darmstadt1 BGP      mesh     up     09:50:01    Established   
gera_greiz1 BGP      mesh     up     23:05:23    Established   
hamburg01 BGP      mesh     up     05:54:37    Established   
hamburg03 BGP      mesh     up     06:09:58    Established   
muenchen1 BGP      mesh     up     2018-02-18  Established   
mwu161   BGP      mesh     up     2018-02-18  Established   
mwu23    BGP      mesh     up     2018-02-18  Established   
mwu7     BGP      mesh     up     04:00:59    Established   
trier1   BGP      mesh     up     2018-02-18  Established   
trier2   BGP      mesh     up     2018-02-18  Established   
vogtland1 BGP      mesh     up     2018-02-18  Established   
vogtland3 BGP      mesh     up     2018-02-18  Established   
vogtland4 BGP      mesh     up     2018-02-18  Established

**Comment by skorpy2009** [comment]
@wusel42 I do not get a "Established", it was online on the 14. - 15.2.

**Comment by andibraeu** [comment]
```
andibraeu@vpn3 ~ % sudo netstat -tpW|grep tincd
tcp        0      0 vpn3.weimarnetz.de:tinc vpn4.leipzig.freifunk.net:33122 VERBUNDEN   19725/tincd     
tcp        0      0 vpn3.weimarnetz.de:42804 a36s.berlin.freifunk.net:656 VERBUNDEN   19725/tincd     
tcp        0      1 vpn3.weimarnetz.de:55196 host.colocrossing.com:658 SYN_SENT    19729/tincd     
tcp        0      0 vpn3.weimarnetz.de:tinc ip4.vpn03b.berlin.freifunk.net:37308 VERBUNDEN   19725/tincd     
tcp        0      0 vpn3.weimarnetz.de:tinc bequerel.routers.chemnitz.freifunk.net:56460 VERBUNDEN   19725/tincd     
tcp6       0      0 vpn3.weimarnetz.de:46334 2001:bf7:b101:1::19:656 VERBUNDEN   19729/tincd     
tcp6       0      0 vpn3.weimarnetz.de:47424 icvpn1.darmstadt.freifunk.net:tinc VERBUNDEN   19725/tincd     
tcp6       0      0 vpn3.weimarnetz.de:35772 gw03.hamburg.freifunk.net:tinc VERBUNDEN   19725/tincd     
tcp6       0      0 vpn3.weimarnetz.de:656  2a01:4f8:150:6208:5054:ff:fe0f:3117:41731 VERBUNDEN   19729/tincd
```

**Comment by skorpy2009** [comment]
@andibraeu this is about the BGP and not the tinc...

**Comment by skorpy2009** [comment]
@andibraeu also you do not have your tinc connected to us:
```
ffadmin@icvpn2:~$ sudo tinc -n icvpn dump connections
berlin2 at 77.87.49.67 port 655 options c socket 12 status c0
bremen5 at 2a01:4f8:151:7104::244 port 46741 options c socket 22 status 1c0
pinneberg1 at 2a02:180:6:1::a8 port 55284 options c socket 27 status 1c0
ruhrgebiet1 at 5.39.121.119 port 52736 options c socket 34 status c0
franken_fff_gw_m1 at 37.120.190.92 port 60615 options c socket 29 status c0
erfurt2 at 217.114.210.177 port 34689 options c socket 14 status c0
bodensee1 at 2a01:4f8:191:40e6::2 port 44818 options c socket 15 status c0
mueritz_bgp1 at 2a01:4f8:191:6323::1:5 port 34314 options c socket 23 status 1c0
stuttgart0401 at 213.239.221.23 port 52036 options c socket 31 status c0
dreilaendereck9 at 144.76.31.247 port 47520 options c socket 32 status c0
vogtland1 at 2003:49:a051::8888 port 34050 options c socket 33 status c0
gera_greiz1 at 2a01:4f8:172:19ea:201::182 port 39414 options c socket 30 status c0
vogtland3 at 2a01:4f8:121:22b3::6:1 port 39324 options c socket 20 status c0
franken_fff_icvpn at 2a01:4f8:162:1369::f3:90 port 49906 options c socket 25 status 1c0
trier2 at 2001:bf7:b201::7 port 60146 options c socket 18 status c0
gera_greiz3 at 2001:41d0:e:8b0::1 port 56124 options c socket 37 status c0
mwu23 at 144.76.209.100 port 39269 options c socket 36 status c0
dreilaendereck3 at 185.89.196.109 port 41630 options c socket 39 status c0
vogtland4 at 88.99.151.81 port 44858 options c socket 40 status c0
trier1 at 77.87.50.12 port 42592 options c socket 42 status c0
hamburg03 at 2001:868:100:d00::20 port 655 options c socket 38 status c0
mwu231 at 136.243.184.91 port 59844 options c socket 28 status 1c0
kreisgt_gut at 2a06:e881:1700:1:400:c0ff:fefb:e275 port 56306 options c socket 13 status c0
luebeck1 at 2a01:4f8:190:4190:5054:ff:fe3f:fea3 port 41998 options c socket 44 status c0
darmstadt1 at 2001:67c:2ed8::48:1 port 48824 options c socket 35 status c0
darmstadt2 at 82.195.73.49 port 44277 options 700000c socket 43 status 100
hamburg01 at 2a00:1f78:c:e::f port 44441 options c socket 26 status c0
stuttgart0503 at 93.186.197.153 port 34448 options c socket 21 status c0
mwu7 at 46.20.37.226 port 45859 options c socket 24 status c0
mwu101 at 94.130.21.201 port 45530 options c socket 41 status c0
waldheim1 at 80.82.209.207 port 60892 options c socket 19 status 1c0
```

**Comment by andibraeu** [comment]
@skorpy2009 do we have to have a connection to you?

you also didn't answer my question...

**Comment by skorpy2009** [comment]
@andibraeu yes you are in the tinc, but since frankfurt2 is a metanode you should be connected to this: https://github.com/freifunk/icvpn/blob/master/metanodes#L3

```
ffadmin@icvpn2:~$ sudo tinc -n icvpn dump reachable nodes | grep weimar
weimar1 id a6b2260dd636 at 2001:bf7:b101:1::35 port 655 cipher 91 digest 64 maclength 4 compression 0 options c status 041a nexthop berlin2 via weimar1 distance 2 pmtu 1391 (min 0 max 1518)
```

Is it possible that both your repositories are not up to date?

**Comment by andibraeu** [comment]
our connections to bgp:

```
weimar1> show ip bgp summary
BGP router identifier 10.207.0.3, local AS number 65042
RIB entries 972, using 106 KiB of memory
Peers 177, using 790 KiB of memory
Peer groups 2, using 64 bytes of memory

Neighbor        V    AS MsgRcvd MsgSent   TblVer  InQ OutQ Up/Down  State/PfxRcd
10.207.0.1      4 65533       0      14        0    0    0 never    Active     
10.207.0.2      4 65041       0      14        0    0    0 never    Active     
10.207.0.4      4 64864       0       0        0    0    0 never    Active     
10.207.0.5      4 44194       0       0        0    0    0 never    Active     
10.207.0.6      4 44194      31     247        0    0    0 00:27:14        0
10.207.0.7      4 65530       0       0        0    0    0 never    Active     
10.207.0.8      4 65530       0       0        0    0    0 never    Active     
10.207.0.9      4 65099       0       0        0    0    0 never    Active     
10.207.0.10     4 65099      30     255        0    0    0 00:27:44        3
10.207.0.11     4 65134       0       0        0    0    0 never    Active     
10.207.0.12     4 65432       0       0        0    0    0 never    Active     
10.207.0.13     4 65046       0       0        0    0    0 never    Active     
10.207.0.14     4 65046       0       0        0    0    0 never    Active     
10.207.0.15     4 64780       0       0        0    0    0 never    Active     
10.207.0.18     4 64525       0       0        0    0    0 never    Active     
10.207.0.19     4 65051       0       0        0    0    0 never    Active     
10.207.0.20     4 65051       0       0        0    0    0 never    Active     
10.207.0.22     4 65511       0       0        0    0    0 never    Active     
10.207.0.23     4 65024       0       0        0    0    0 never    Active     
10.207.0.25     4 64858       0       0        0    0    0 never    Active     
10.207.0.30     4 65433     779     152        0    0    0 00:27:48      216
10.207.0.34     4 65034       0       0        0    0    0 never    Active     
10.207.0.35     4 65026       0       0        0    0    0 never    Active     
10.207.0.36     4 65053      35     264        0    0    0 00:27:47        2
10.207.0.37     4 65037       0      14        0    0    0 never    Active     
10.207.0.38     4 65513       0       0        0    0    0 never    Active     
10.207.0.40     4 65380       0       0        0    0    0 never    Active     
10.207.0.41     4 65380       0       0        0    0    0 never    Active     
10.207.0.42     4 65142       0       0        0    0    0 never    Active     
10.207.0.44     4 65251       0      14        0    0    0 never    Active     
10.207.0.45     4 65210     729     168        0    0    0 00:25:43        0
10.207.0.46     4 65210     734     168        0    0    0 00:25:43      217
10.207.0.47     4 65210       0       0        0    0    0 never    Active     
10.207.0.51     4 65054       0       0        0    0    0 never    Active     
10.207.0.55     4 65530       0       0        0    0    0 never    Active     
10.207.0.56     4 65036       0       0        0    0    0 never    Active     
10.207.0.57     4 65528       0       0        0    0    0 never    Active     
10.207.0.58     4 65529       0       0        0    0    0 never    Active     
10.207.0.59     4 65529       0       0        0    0    0 never    Active     
10.207.0.61     4 49009     559     250        0    0    0 00:27:43      173
10.207.0.63     4 49009     586     244        0    0    0 00:27:46      172
10.207.0.64     4 49009       0       0        0    0    0 never    Active     
10.207.0.68     4 65050       0       0        0    0    0 never    Active     
10.207.0.71     4 65043     634      91        0    0    0 00:27:12      214
10.207.0.73     4 65523       0       0        0    0    0 never    Active     
10.207.0.74     4 65043     678     170        0    0    0 00:27:06      214
10.207.0.75     4 65043       0       0        0    0    0 never    Active
```

**Comment by skorpy2009** [comment]
@andibraeu aperantly your config is not up to date:

frankfurt:
```
asn: 65026
bgp:
  frankfurt2:
    ipv4: 10.207.0.1
    ipv6: fec0::a:cf:0:1
```

```
ffadmin@icvpn2:~$ sudo birdc show protocols all icvpn_weimar1
BIRD 1.6.3 ready.
name     proto    table    state  since       info
icvpn_weimar1 BGP      master   start  1519059735  Idle          Received: Bad peer AS
  Preference:     100
  Input filter:   (unnamed)
  Output filter:  (unnamed)
  Routes:         0 imported, 0 filtered, 0 exported, 0 preferred
  Route change stats:     received   rejected   filtered    ignored   accepted
    Import updates:              0          0          0          0          0
    Import withdraws:            0          0        ---          0          0
    Export updates:              0          0          0        ---          0
    Export withdraws:            0        ---        ---        ---          0
  BGP state:          Idle
    Neighbor address: 10.207.0.3
    Neighbor AS:      65042
    Error wait:       26/300
    Last error:       Received: Bad peer AS
```

**Comment by andibraeu** [comment]
I updated the bgp config

**Comment by skorpy2009** [comment]
@andibraeu BGP v4 is only. BGP for v6 is still down, will you also fix this or shell we remove your IPv6 BGP Config?

**Comment by andibraeu** [comment]
ipv6 is WIP. Just let it in there.

I really don't understand the pressure here...

**Comment by hipposen** [comment]
erfurt will also be active! so don't deactivate it.

**Comment by andibraeu** [comment]
I'd like to veto against merging this pull request! See the discussion at the mailing list

**Comment by skorpy2009** [comment]
@hipposen I can ping your Node but no BGP Session gets up, when will this change?

**Comment by hipposen** [comment]
i test it on 20th with andi from weimar - it works like expected - how do you test the connection? you can try to access 10.99.4.21.

**Comment by Nurtic-Vibe** [comment]
rhein-neckar will come back in next 2-4 weeks

**Comment by skorpy2009** [comment]
The following are still down for me. Either they are not updating there repos or the bgp is fully down:

```
icvpn_aachen1 BGP      master   start  1532215919  Passive
icvpn_amsterdam1 BGP      master   start  1532215919  Passive
icvpn_augsburg1 BGP      master   start  1532215919  Passive
icvpn_berlin1 BGP      master   start  1532215919  Passive
icvpn_berlin2 BGP      master   start  1532215919  Passive
icvpn_bielefeldbgp1 BGP      master   start  1532215919  Passive
icvpn_bitburg1 BGP      master   start  1532215919  Passive
icvpn_bodensee1 BGP      master   start  1532215919  Passive
icvpn_celle1 BGP      master   start  1532215919  Passive
icvpn_chemnitz1 BGP      master   start  1532215919  Passive
icvpn_franken_fff_gw_m4 BGP      master   start  1532215919  Passive
icvpn_hamburg02 BGP      master   start  1532215919  Passive
icvpn_hamburg03 BGP      master   start  1532215919  Passive
icvpn_innsbruck_ffibk1 BGP      master   start  1532215919  Passive
icvpn_innsbruck_ffibk2 BGP      master   start  1532215919  Passive
icvpn_jena1 BGP      master   start  1532215919  Passive
icvpn_kiel0 BGP      master   start  1532215919  Passive
icvpn_moehne1 BGP      master   start  1532215919  Passive
icvpn_muenchen1 BGP      master   start  1532215919  Passive
icvpn_rhein_neckar BGP      master   start  1532215919  Passive
icvpn_ruhrgebiet1 BGP      master   start  1532215919  Passive
icvpn_stuttgart0401 BGP      master   start  1532353582  Idle          Received: Bad peer AS
icvpn_trier1 BGP      master   start  1532215919  Passive
icvpn_ulm10 BGP      master   start  1532215919  Passive
icvpn_waldheim2 BGP      master   start  1532215919  Passive
icvpn_zollernalb1 BGP      master   start  1532215919  Passive
icvpn_zollernalb2 BGP      master   start  1532215919  Passive
icvpn_leipzig2 BGP      master   start  1532353485  Idle          Received: Bad peer AS
icvpn_pinneberg BGP      master   start  1532251807  Passive
```

**Comment by Ranlvor** [comment]
If we want findfree to only give free IP-Addresses as recomendations, we should keep ulm10, leipzig2 and bremen6. All other hosts do not even ping and should be deleted.

I'd say „go for merge“

**Comment by andibraeu** [comment]
will you do an announcement on the icvpn mailing list before finally merging?

**Comment by skorpy2009** [comment]
@andibraeu I sent an announcement to the icvpn mailing list

**Pull request merged**
