### PR TITLE
- Quote 020 domain name

### PR DESCRIPTION
**Pull request by qrah**
- add secondary dns
- add wg and adm domains

### CODE REVIEW

**Comment by mweinelt** [comment]
Two character TLDs are reserved for ccTLDs (ISO3166) and I don't see us breaking that rule, to be honest.

**Comment by mmunz** [comment]
I wouldn't care about two letters, but .wg is indeed suboptimal. Afaik it is not in use right now, but it is reserved for West Jordan and Gaza.

**Comment by mweinelt** [comment]
Also `.adm` could become a gTLD any day, because its short for `admin`. What about `.ams` instead? I don't think that will become a problem because there is already `.amsterdam`.

**Comment by wusel42** [comment]
Well, since ICANN opened that box of pandora's, there's no such thing as an "unlikely to become public" TLD besides those that are reserved, is it? That in mind, policy here should adhere to "no two letter domains" (which are there for countries/regions/whatever politicans consider fit into this) and then either "no 'private' ones at all" or "only if non-conflicting as date of entry", imho. Anything else I find difficult to argue.

But then, this repo is only a suggestion anyway, therefore I'd prefer "anything goes that's not conflicting with an official TLD as of date of entry" (dig NS adm. @i.root-servers.net. => NXDOMAIN => all fine.)

**Comment by stpq** [comment]
adm... hmm... i think i will have to wait till the time the adm will become a gTLD, than change it. We use it on our intranet for quite a while, it would (will) be an issue to make people used to the change.

step (admamsterdam.org)

**Comment by mweinelt** [comment]
Can you please remove the <code>wg.<code> TLD so we can merge the rest for now?

**Comment by qrah** [comment]
.wg should be removed now

**Pull request merged**
