### PR TITLE
berlin: add more ipv4 addresses.

### PR DESCRIPTION
**Pull request by pmelange**
The address space for Berlin, which has since many years (since 2014) been
limited to 3x /16 spaces.  As the network is growing, we have noticed
a severe lack of available adresses.

This adds 10.248.0.0/14 to the Berlin network.

Signed-off-by: Perry Melange <isprotejesvalkata@gmail.com>

### CODE REVIEW

**Comment by pmelange** [comment]
@mweinelt Is there any chance that you can take a look at the PR?

**Comment by mweinelt** [comment]
I need to give up this role, I stopped caring about it a long time ago.

**Comment by wusel42** [comment]
Moin,

hmm, unsure about why DCO stuff was enable here in the first place, but AFAICS it fails because:

> Commit sha: [931ee81](https://github.com/freifunk/icvpn-meta/pull/623/commits/931ee81f40978e22acbc30dd61cb70ef7759f717), Author: pmelange, Committer: pmelange; Expected "pmelange [isprotejesvalkata@gmail.com](mailto:isprotejesvalkata@gmail.com)", but got "Perry Melange [isprotejesvalkata@gmail.com](mailto:isprotejesvalkata@gmail.com)".

Would state this a false-negative, as, seemingly, the email addresses match — what is what counts, according to https://github.com/apps/dco. According to sha256sum, the email addresses are identical.

But, well, please fix your PR to make DCO happy again, while we discuss if or how to proceed with that check: Personally, I don't see any use in applying DCO check in this repo and would vote to remove that weirdo; @mweinelt, @Ranlvor, @leeps, @thomasDOTwtf, your opinion on that?

**Comment by pmelange** [comment]
Ok, so I changed the commit author and the signed-off.  It passes DCO.  @wusel42 , thanks for taking a look at the PR and hopefully Berlin can start using the new IP's soon. :)

**Comment by wusel42** [comment]
Have fun.

**Pull request merged**
