### PR TITLE
Großreinemachen

### PR DESCRIPTION
**Pull request by kpanic23**
Commented out all BGP peers being inactive since at least July 14th
according to http://lg.ff3l.net/summary/gw9/ipv4

### CODE REVIEW

**Comment by mmunz** [comment]
How do you determine "inactive"? To me it looks like most hosts showing state "Start" on that page just have no peerings set up with that bgp instance. At least for augsburg1 i can tell that it is up and has active peerings.

**Comment by kpanic23** [comment]
Actually, yes, augsburg1 is the only one of those "inactive" hosts I removed which indeed seems to be running, but does not seem to use and/or update the icvpn-meta.
Darmstadt does not have a session to this peer either, according to https://paste.linuxlounge.net/#/8XzZvgY1U0ObZBAv1IZi4cyuBmA!lzsCI1HgXipKYqKQ2I9MFYwPPW4jWZr77gObD3yGzMU
So what use is a peer definition in the meta if the peer itself does not use the meta?

**Comment by mweinelt** [comment]
darmstadt1 is exactly one year old today. It's ip addresses were used by darmstadt4 for a year before that and still peers like Augsburg haven't managed to set up a peering. So the question really is: why bother? What's the point?

If communities aren't updating their configurations they potentially damage the network, like what is currently happening to the tinc-based transfer network. Peers are introducing their host files to the mesh, that were already removed in the repository. This is meh!

**Comment by Ranlvor** [comment]
ACK

**Pull request merged**
