### PR TITLE
Update vfnnrw

### PR DESCRIPTION
**Pull request by RubenKelevra**

### CODE REVIEW

**Comment by mweinelt** [comment]
I'm not really sure why are you are in need of some many allocations. Please help me understand.

**Comment by tcatm** [comment]
Please allocate only subnets you are actually planning to use. You may also allocate bigger subnetz (e.g. /14) to simplify the setup a little if you really need that much space.

IPv6 from 2001:bf7::/32 is allocated by Freifunk Berlin. I'd suggest using a /44 instead of several /64 there. That should be plenty.

**Comment by thomasDOTde** [comment]
Many of the claimed addressing needs a already covered by another community or meta community  holding the needed ip space.
+    - 10.0.0.0/16 -> Community is already active in Portugal and Meta Community Ruhrgebiet (Oberhausen is organized in Ruhrgebiet)
+    - 10.1.0.0/16 -> Community in Gelsenkirchen is organized inside of Meta Community Ruhrgebiet
+    - 10.82.0.0/16 -> Community in Gelsenkirchen is organized inside of Meta Community Ruhrgebiet
+    - 10.91.0.0/16 -> Alread in use by Reseaucitoyen Brussels Belgium
+    - 10.92.0.0/16 -> I'm not seeing any activity in Froendenberg
+    - 10.147.0.0/16 -> As far as I know Freifunk Duesseldorf is organized in Rheinufer
+    - 10.151.0.0/16 -> Community in Bochum is organized inside of Meta Community Ruhrgebiet
+    - 10.154.0.0/16 -> Community in Hagen is organized inside of Meta Community Ruhrgebiet

**Comment by RubenKelevra** [comment]
@mweinelt well this is just a update of our existing installations ... not allocating now that many subnets.

@tcatm will discuss the /14 idea, I think that would be a good solution. We own a /44 Subnet from Berlin, but we devide it for every community in one /64, this is what we announce. Announce /44 and route seperatly would be more technical effort on configuring our gateways.

@thomasDOTde 

10.0.0.0/16 the conflict with portugal was solved, they said they dont want to be part of the ic-vpn. FFRL has overwritten our defintion for a running network, which is on since 2013...
https://wiki.freifunk.net/index.php?title=IP-Netze&diff=26424&oldid=26423

10.1.0.0/16 Gelsenkirchen moved to FFRL, so I will delete this claim soon when I had the time to make sure that I don't unplug any of our member-nodes with this step.
10.82.0.0/16 is Recklinghausen, we have some nodes there ... "Meta Community Ruhrgebiet" is very large, so there are overlappings, Recklinghausen might be one. 
10.91.0.0/16 I know, 5 networks are merging a.t.m. to 10.221.0.0/16, 10.91.0.0/16 is one of them.
10.92.0.0/16 community in fröndenberg is on creation at the moment.
10.147.0.0/16 yes, but we had a new member which doesn't want to join this community ... so I had create a subnet for the three nodes.
10.151.0.0/16 there a new active community creating there ... "Meta Community Ruhrgebiet" is just overlapping.
10.154.0.0/16 same as 10.151.0.0/16

**Comment by tcatm** [comment]
Are all these subnets announced from the same AS (65530)? If so, there must be some AS-internal routing where you could route smaller prefixes from a /44 wherever needed. A /44 is really big.

**Comment by wusel42** [comment]
I'd agree that only a summary prefix should be announced/listed. As for the number of networks, if vfnnrw intends to provide a backbone-like architecture for their users, I think that's fine. If really 23 /16 are needed is another discussion; but as currently it's usually one /16 per community per current policies, I can't object.

**Comment by mweinelt** [comment]
I'd feel better if the allocations included a comment which exact community they are being used for, as this is being made very unclear by that large allocation.

Other than that, I agree that if this is a backbone-like approach and for every subnet their exists a community and there are no collisions, I would not object either.

**Comment by RubenKelevra** [comment]
Updated definitions

**Comment by mweinelt** [comment]
Syntax is still wrong. I highlighted you several times on IRC concerning this.

**Comment by ohrensessel** [comment]
@RubenKelevra I do not understand your comments. what does the following mean? You mention it for several subnets.

> "Meta Community Ruhrgebiet" is just overlapping.

**Comment by ohrensessel** [comment]
for the number of allocations here: I would strongly object to allocate a /16 here for something like the following

> 10.147.0.0/16 yes, but we had a new member which doesn't want to join this community ... so I had create a subnet for the three nodes.

there seems to be a single person not wanting to join a certain local community. this is no reason to allocate a /16 subnet, I don't see a use case here.

**Comment by wusel42** [comment]
@ohrensessel I don't think github is the right place for policy discussions; as it is today, a community allocates what it (thinks it) needs via the Wiki-Table. If that's done, that allocation is vaild, period.

Reason I'm not merging is: "Failed — The Travis CI build failed". @RubenKelevra please check the Travis output, see @mweinelt 's comment earlier.

**Comment by ohrensessel** [comment]
not if there are conflicts, which is my impression from the comments here. conflicts should not be merged

**Comment by RubenKelevra** [comment]
@ohrensessel Aufgrund deines Nicks denke ich mal, Deutsch ist an der Stelle auch okay. Dann brech ich mir nicht so einen ab.

Wir als Verein helfen ja nur neuen Leuten irgendwomit zu starten, wir versuchen zu verifizieren, dass es keine Community gibt, und wenn versuchen wir die Leute an die bestehende Community zu vermitteln.

Und dann gibts auch noch solche Spezialfälle wie, wir helfen jemandem 1-2 Nodes aufzustellen und um den herum bildet sich eine aktive Community. 

Die Sache ist die, ich betreue nur die Technische Infrastruktur, wir ist es Wurst wer wo Probleme mit wem hat. In letzter Zeit gibt es relativ viel gehate gegen mich, weil ich die Registrierungen für die Leute durchführe, das liegt daran das ich nunmal die Arbeit an der Stelle erledige.

Wenn es jetzt Konflikte gibt, weil es im Freifunk-Rheinland Meta-Communitys gibt, die ganze Landstriche umfassen, dann ändert das nichts daran das es dort nicht unbedingt eine Community gibt. Und entsprechend gibt es Überlappungen.

Hoffe ich konnte ein bisschen Licht in die Sache bringen, wenn du Fragen zu speziellen Netzen hast, richte die gerne an kontakt@freifunk-nrw.de, und jemand im Vorstand vermittelt dann deine Anfrage :)


LG Ruben

**Pull request merged**
